src/Models/ErrorViewModel.cs
namespace Gestão_Financeira.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace Gestão_Financeira.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Digite o e-mail!")]
        public string Email1 { get; set; }
        [Required(ErrorMessage = "Digite a senha!")]
        public string Senha { get; set; }

        

    }
}

src/Models/UserModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Gestão_Financeira.Models
{
    public class UserModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do usuário!")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o apelido do usuário!")]
        public string Apelido { get; set; }
        [Required(ErrorMessage = "Digite a senha do usuário!")]
        public string Senha { get; set; }
        [Required(ErrorMessage = "Digite o e-mail do usuário!")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido!")]
        public string Email { get; set; }


        public bool SenhaValida(string senha)
        {
            return Senha == senha;
        }

    }
}

src/Controllers/ComoFuncionaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gestão_Financeira.Controllers
{
    public class ComoFunciona : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/HomeController.cs
using Gestão_Financeira.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gestão_Financeira.Controllers
{
    public class HomeController : Controller
    {
        

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Controllers/HomeLogadoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gestão_Financeira.Controllers
{
    public class HomeLogadoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/QuemSomosController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gestão_Financeira.Controllers
{
    public class QuemSomosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Views/Cadastro/Index.cshtml
@model UserModel
@{
    ViewData["Title"] = "Cadastro";
}
<form asp-controller="Cadastro" asp-action="Criar" method="post"> 
    <p class="text-center">Insira suas informações abaixo!</p>
  <div class="mb-3">
    <label for="exampleInputName" class="form-label">Nome Completo</label>
    <input type="text" asp-for="Nome" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputName" class="form-label">Nome de usuário</label>
    <input type="text" asp-for="Apelido" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email</label>
    <input type="email" asp-for="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Senha</label>
    <input type="password" asp-for="Senha" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Confirme sua senha</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/Views/ComoFunciona/Index.cshtml
@{
    ViewData["Title"] = "Como funciona";
    Layout = "_LayoutDeslogado";
}

src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
    Layout = "_LayoutDeslogado";
}

<div class="text-center">
    <h1 class="display-4">Gestão Financeira</h1>
    <p>Controle suas finanças para uma melhor qualidade de vida!</p>
</div>
<div class="text-center">
    <a class="btn btn-primary btn-lg" asp-controller="Login" asp-action="Index">Fazer login</a>
    <a class="btn btn-secondary btn-lg" asp-controller="Cadastro" asp-action="Index">Cadastre-se</a>
</div>

src/Views/HomeLogado/Index.cshtml
@{
}

src/Views/Login/Index.cshtml
@model LoginModel
@{
    ViewData["Title"] = "Login";
    Layout = "_LayoutLogin";
}

@if (TempData["MensagemErro"] != null){
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="Login" asp-action="Entrar" method="post">
  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" asp-for="Email1" class="form-control" id="email1" aria-describedby="emailHelp">
    @Html.ValidationMessageFor(x => x.Email1)
  </div>
  <div class="mb-3">
    <label  class="form-label">Senha</label>
    <input type="password" asp-for="Senha" class="form-control" id="senha">
        @Html.ValidationMessageFor(x => x.Senha)
  </div>
  <button type="submit" class="btn btn-primary">Entrar</button>
</form>

src/Views/QuemSomos/Index.cshtml
@{
    ViewData["Title"] = "Quem somos";
    Layout = "_LayoutDeslogado";
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão Financeira</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gestão_Financeira.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestão Financeira</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestão Financeira 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão Financeira</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gestão_Financeira.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestão Financeira</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ComoFunciona" asp-action="Index">Como Funciona</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QuemSomos" asp-action="Index">Quem somos</a>
                        </li>
                    </ul>
                </div>
                <div class="text-end">
                    <a class="btn btn-primary btn-sm" asp-controller="Login" asp-action="Index">Fazer login</a>
                    <a class="btn btn-secondary btn-sm" asp-controller="Cadastro" asp-action="Index">Cadastre-se</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestão Financeira 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão Financeira</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gestão_Financeira.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestão Financeira</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ComoFunciona" asp-action="Index">Como Funciona</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QuemSomos" asp-action="Index">Quem somos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestão Financeira 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>